#pragma once
/**
 * @file PacketDebugRegGen.h
 * @brief AUTO-GENERATED - Do not edit manually!
 * 
 * Generated by: generate_packet_debug.py
 * Re-run the script after modifying packet.h
 *
 * Stats: 129 with struct, 11 header-only,
 *        19 variable-size, 20 no struct found
 */

#ifndef __PACKET_DEBUG_REG_GEN_H__
#define __PACKET_DEBUG_REG_GEN_H__

#include "../../Lead-Shared-Source/packet.h"

//=============================================================================
// Fallback Printers
//=============================================================================
inline void PrintHexDump(FILE* f, const void* data, int size) {
    if (size <= 1) { fprintf(f, "(empty)\n"); return; }
    const BYTE* bytes = (const BYTE*)data;
    int maxBytes = (size - 1 > 24) ? 24 : size - 1;
    for (int i = 1; i <= maxBytes; i++) fprintf(f, "%02X ", bytes[i]);
    if (size - 1 > 24) fprintf(f, "...");
    fprintf(f, "\n");
}

inline void PrintHeaderOnly(FILE* f, const void* data, int size) {
    fprintf(f, "(header only)\n");
}

//=============================================================================
// Auto-Generated Printer Functions (157 structs)
//=============================================================================
inline void Print_TPacketCGLogin(FILE* f, const void* data, int size) {
    const TPacketCGLogin& p = *(const TPacketCGLogin*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGAttack(FILE* f, const void* data, int size) {
    const TPacketCGAttack& p = *(const TPacketCGAttack*)data;
    fprintf(f, "bType=%u dwVID=%u bCRCMagicCubeProcPiece=%u bCRCMagicCubeFilePiece=%u\n", p.bType, p.dwVID, p.bCRCMagicCubeProcPiece, p.bCRCMagicCubeFilePiece);
}

inline void Print_TPacketCGChat(FILE* f, const void* data, int size) {
    const TPacketCGChat& p = *(const TPacketCGChat*)data;
    fprintf(f, "size=%u type=%u\n", p.size, p.type);
}

inline void Print_TPacketCGCharacterCreate(FILE* f, const void* data, int size) {
    const TPacketCGCharacterCreate& p = *(const TPacketCGCharacterCreate*)data;
    fprintf(f, "index=%u job=%u shape=%u Con=%u Int=%u Str=%u Dex=%u\n", p.index, p.job, p.shape, p.Con, p.Int, p.Str, p.Dex);
}

inline void Print_TPacketCGCharacterDelete(FILE* f, const void* data, int size) {
    const TPacketCGCharacterDelete& p = *(const TPacketCGCharacterDelete*)data;
    fprintf(f, "index=%u private_code='%s'\n", p.index, p.private_code);
}

inline void Print_TPacketCGCharacterSelect(FILE* f, const void* data, int size) {
    const TPacketCGCharacterSelect& p = *(const TPacketCGCharacterSelect*)data;
    fprintf(f, "index=%u\n", p.index);
}

inline void Print_TPacketCGMove(FILE* f, const void* data, int size) {
    const TPacketCGMove& p = *(const TPacketCGMove*)data;
    fprintf(f, "bFunc=%u bArg=%u bRot=%u lX=%d lY=%d dwTime=%u\n", p.bFunc, p.bArg, p.bRot, p.lX, p.lY, p.dwTime);
}

inline void Print_TPacketCGSyncPosition(FILE* f, const void* data, int size) {
    const TPacketCGSyncPosition& p = *(const TPacketCGSyncPosition*)data;
    fprintf(f, "wSize=%u\n", p.wSize);
}

inline void Print_TPacketCGEntergame(FILE* f, const void* data, int size) {
    const TPacketCGEntergame& p = *(const TPacketCGEntergame*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGItemUse(FILE* f, const void* data, int size) {
    const TPacketCGItemUse& p = *(const TPacketCGItemUse*)data;
    fprintf(f, "Cell=(struct)\n");
}

inline void Print_TPacketCGItemMove(FILE* f, const void* data, int size) {
    const TPacketCGItemMove& p = *(const TPacketCGItemMove*)data;
    fprintf(f, "Cell=(struct) CellTo=(struct) count=%u\n", (unsigned)p.count);
}

inline void Print_TPacketCGItemPickup(FILE* f, const void* data, int size) {
    const TPacketCGItemPickup& p = *(const TPacketCGItemPickup*)data;
    fprintf(f, "vid=%u\n", p.vid);
}

inline void Print_TPacketCGQuickslotAdd(FILE* f, const void* data, int size) {
    const TPacketCGQuickslotAdd& p = *(const TPacketCGQuickslotAdd*)data;
    fprintf(f, "pos=%u slot=(struct)\n", p.pos);
}

inline void Print_TPacketCGQuickslotDel(FILE* f, const void* data, int size) {
    const TPacketCGQuickslotDel& p = *(const TPacketCGQuickslotDel*)data;
    fprintf(f, "pos=%u\n", p.pos);
}

inline void Print_TPacketCGQuickslotSwap(FILE* f, const void* data, int size) {
    const TPacketCGQuickslotSwap& p = *(const TPacketCGQuickslotSwap*)data;
    fprintf(f, "pos=%u change_pos=%u\n", p.pos, p.change_pos);
}

inline void Print_TPacketCGWhisper(FILE* f, const void* data, int size) {
    const TPacketCGWhisper& p = *(const TPacketCGWhisper*)data;
    fprintf(f, "wSize=%u\n", p.wSize);
}

inline void Print_TPacketCGItemDrop(FILE* f, const void* data, int size) {
    const TPacketCGItemDrop& p = *(const TPacketCGItemDrop*)data;
    fprintf(f, "Cell=(struct) gold=%u count=%u\n", p.gold, (unsigned)p.count);
}

inline void Print_TPacketCGOnClick(FILE* f, const void* data, int size) {
    const TPacketCGOnClick& p = *(const TPacketCGOnClick*)data;
    fprintf(f, "vid=%u\n", p.vid);
}

inline void Print_TPacketCGExchange(FILE* f, const void* data, int size) {
    const TPacketCGExchange& p = *(const TPacketCGExchange*)data;
    fprintf(f, "sub_header=%u arg1=%u arg2=%u Pos=(struct)\n", p.sub_header, p.arg1, p.arg2);
}

inline void Print_TPacketCGCharacterPosition(FILE* f, const void* data, int size) {
    const TPacketCGCharacterPosition& p = *(const TPacketCGCharacterPosition*)data;
    fprintf(f, "position=%u\n", p.position);
}

inline void Print_TPacketCGScriptAnswer(FILE* f, const void* data, int size) {
    const TPacketCGScriptAnswer& p = *(const TPacketCGScriptAnswer*)data;
    fprintf(f, "answer=%u\n", p.answer);
}

inline void Print_TPacketCGQuestInputString(FILE* f, const void* data, int size) {
    const TPacketCGQuestInputString& p = *(const TPacketCGQuestInputString*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGQuestConfirm(FILE* f, const void* data, int size) {
    const TPacketCGQuestConfirm& p = *(const TPacketCGQuestConfirm*)data;
    fprintf(f, "answer=%u requestPID=%u\n", p.answer, p.requestPID);
}

inline void Print_TPacketCGShop(FILE* f, const void* data, int size) {
    const TPacketCGShop& p = *(const TPacketCGShop*)data;
    fprintf(f, "subheader=%u\n", p.subheader);
}

inline void Print_TPacketCGUseSkill(FILE* f, const void* data, int size) {
    const TPacketCGUseSkill& p = *(const TPacketCGUseSkill*)data;
    fprintf(f, "dwVnum=%u dwVID=%u\n", p.dwVnum, p.dwVID);
}

inline void Print_TPacketCGAddFlyTargeting(FILE* f, const void* data, int size) {
    const TPacketCGAddFlyTargeting& p = *(const TPacketCGAddFlyTargeting*)data;
    fprintf(f, "dwTargetVID=%u\n", p.dwTargetVID);
}

inline void Print_TPacketCGShoot(FILE* f, const void* data, int size) {
    const TPacketCGShoot& p = *(const TPacketCGShoot*)data;
    fprintf(f, "bType=%u\n", p.bType);
}

inline void Print_SPacketCGMyShop(FILE* f, const void* data, int size) {
    const SPacketCGMyShop& p = *(const SPacketCGMyShop*)data;
    fprintf(f, "bCount=%u\n", p.bCount);
}

inline void Print_TPacketCGTargetInfoLoad(FILE* f, const void* data, int size) {
    const TPacketCGTargetInfoLoad& p = *(const TPacketCGTargetInfoLoad*)data;
    fprintf(f, "dwVID=%u\n", p.dwVID);
}

inline void Print_TPacketCGItemUseToItem(FILE* f, const void* data, int size) {
    const TPacketCGItemUseToItem& p = *(const TPacketCGItemUseToItem*)data;
    fprintf(f, "Cell=(struct) TargetCell=(struct)\n");
}

inline void Print_TPacketCGTarget(FILE* f, const void* data, int size) {
    const TPacketCGTarget& p = *(const TPacketCGTarget*)data;
    fprintf(f, "dwVID=%u\n", p.dwVID);
}

inline void Print_TPacketCGWarp(FILE* f, const void* data, int size) {
    const TPacketCGWarp& p = *(const TPacketCGWarp*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGScriptButton(FILE* f, const void* data, int size) {
    const TPacketCGScriptButton& p = *(const TPacketCGScriptButton*)data;
    fprintf(f, "idx=%u\n", (unsigned)p.idx);
}

inline void Print_TPacketCGMessenger(FILE* f, const void* data, int size) {
    const TPacketCGMessenger& p = *(const TPacketCGMessenger*)data;
    fprintf(f, "subheader=%u\n", p.subheader);
}

inline void Print_TPacketCGSafeboxCheckin(FILE* f, const void* data, int size) {
    const TPacketCGSafeboxCheckin& p = *(const TPacketCGSafeboxCheckin*)data;
    fprintf(f, "bSafePos=%u ItemPos=(struct)\n", p.bSafePos);
}

inline void Print_TPacketCGSafeboxCheckout(FILE* f, const void* data, int size) {
    const TPacketCGSafeboxCheckout& p = *(const TPacketCGSafeboxCheckout*)data;
    fprintf(f, "bSafePos=%u ItemPos=(struct)\n", p.bSafePos);
}

inline void Print_TPacketCGPartyInvite(FILE* f, const void* data, int size) {
    const TPacketCGPartyInvite& p = *(const TPacketCGPartyInvite*)data;
    fprintf(f, "vid=%u\n", p.vid);
}

inline void Print_TPacketCGPartyInviteAnswer(FILE* f, const void* data, int size) {
    const TPacketCGPartyInviteAnswer& p = *(const TPacketCGPartyInviteAnswer*)data;
    fprintf(f, "leader_vid=%u accept=%u\n", p.leader_vid, p.accept);
}

inline void Print_TPacketCGPartyRemove(FILE* f, const void* data, int size) {
    const TPacketCGPartyRemove& p = *(const TPacketCGPartyRemove*)data;
    fprintf(f, "pid=%u\n", p.pid);
}

inline void Print_TPacketCGPartySetState(FILE* f, const void* data, int size) {
    const TPacketCGPartySetState& p = *(const TPacketCGPartySetState*)data;
    fprintf(f, "pid=%u byRole=%u flag=%u\n", p.pid, p.byRole, p.flag);
}

inline void Print_TPacketCGPartyUseSkill(FILE* f, const void* data, int size) {
    const TPacketCGPartyUseSkill& p = *(const TPacketCGPartyUseSkill*)data;
    fprintf(f, "bySkillIndex=%u vid=%u\n", p.bySkillIndex, p.vid);
}

inline void Print_TPacketCGPartyParameter(FILE* f, const void* data, int size) {
    const TPacketCGPartyParameter& p = *(const TPacketCGPartyParameter*)data;
    fprintf(f, "bDistributeMode=%u\n", p.bDistributeMode);
}

inline void Print_TPacketCGGuild(FILE* f, const void* data, int size) {
    const TPacketCGGuild& p = *(const TPacketCGGuild*)data;
    fprintf(f, "subheader=%u\n", p.subheader);
}

inline void Print_TPacketCGAnswerMakeGuild(FILE* f, const void* data, int size) {
    const TPacketCGAnswerMakeGuild& p = *(const TPacketCGAnswerMakeGuild*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGFishing(FILE* f, const void* data, int size) {
    const TPacketCGFishing& p = *(const TPacketCGFishing*)data;
    fprintf(f, "dir=%u\n", p.dir);
}

inline void Print_TPacketCGGiveItem(FILE* f, const void* data, int size) {
    const TPacketCGGiveItem& p = *(const TPacketCGGiveItem*)data;
    fprintf(f, "byHeader=%u dwTargetVID=%u ItemPos=(struct) byItemCount=%u\n", p.byHeader, p.dwTargetVID, p.byItemCount);
}

inline void Print_TPacketCGEmpire(FILE* f, const void* data, int size) {
    const TPacketCGEmpire& p = *(const TPacketCGEmpire*)data;
    fprintf(f, "bEmpire=%u\n", p.bEmpire);
}

inline void Print_TPacketCGRefine(FILE* f, const void* data, int size) {
    const TPacketCGRefine& p = *(const TPacketCGRefine*)data;
    fprintf(f, "pos=%u type=%u\n", (unsigned)p.pos, p.type);
}

inline void Print_TPacketCGMarkLogin(FILE* f, const void* data, int size) {
    const TPacketCGMarkLogin& p = *(const TPacketCGMarkLogin*)data;
    fprintf(f, "handle=%u random_key=%u\n", p.handle, p.random_key);
}

inline void Print_TPacketCGMarkCrclist(FILE* f, const void* data, int size) {
    const TPacketCGMarkCrclist& p = *(const TPacketCGMarkCrclist*)data;
    fprintf(f, "imgIdx=%u crclist=[80]\n", p.imgIdx);
}

inline void Print_TPacketCGMarkUpload(FILE* f, const void* data, int size) {
    const TPacketCGMarkUpload& p = *(const TPacketCGMarkUpload*)data;
    fprintf(f, "gid=%u\n", p.gid);
}

inline void Print_TPacketCGMarkIdxlist(FILE* f, const void* data, int size) {
    const TPacketCGMarkIdxlist& p = *(const TPacketCGMarkIdxlist*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGHack(FILE* f, const void* data, int size) {
    const TPacketCGHack& p = *(const TPacketCGHack*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGChangeName(FILE* f, const void* data, int size) {
    const TPacketCGChangeName& p = *(const TPacketCGChangeName*)data;
    fprintf(f, "index=%u\n", p.index);
}

inline void Print_TPacketCGLogin2(FILE* f, const void* data, int size) {
    const TPacketCGLogin2& p = *(const TPacketCGLogin2*)data;
    fprintf(f, "dwLoginKey=%u adwClientKey=[4]\n", p.dwLoginKey);
}

inline void Print_TPacketCGLogin3(FILE* f, const void* data, int size) {
    const TPacketCGLogin3& p = *(const TPacketCGLogin3*)data;
    fprintf(f, "adwClientKey=[4]\n");
}

inline void Print_TPacketCGGuildSymbolUpload(FILE* f, const void* data, int size) {
    const TPacketCGGuildSymbolUpload& p = *(const TPacketCGGuildSymbolUpload*)data;
    fprintf(f, "size=%u guild_id=%u\n", p.size, p.guild_id);
}

inline void Print_TPacketCGSymbolCrc(FILE* f, const void* data, int size) {
    const TPacketCGSymbolCrc& p = *(const TPacketCGSymbolCrc*)data;
    fprintf(f, "guild_id=%u crc=%u size=%u\n", p.guild_id, p.crc, p.size);
}

inline void Print_TPacketCGScriptSelectItem(FILE* f, const void* data, int size) {
    const TPacketCGScriptSelectItem& p = *(const TPacketCGScriptSelectItem*)data;
    fprintf(f, "selection=%u\n", p.selection);
}

inline void Print_TPacketCGSwitchbot(FILE* f, const void* data, int size) {
    const TPacketCGSwitchbot& p = *(const TPacketCGSwitchbot*)data;
    fprintf(f, "size=%d subheader=%u slot=%u\n", p.size, p.subheader, p.slot);
}

inline void Print_TPacketCGDragonSoulRefine(FILE* f, const void* data, int size) {
    const TPacketCGDragonSoulRefine& p = *(const TPacketCGDragonSoulRefine*)data;
    fprintf(f, "bSubType=%u ItemGrid=(struct)\n", p.bSubType);
}

inline void Print_SPacketCGStateCheck(FILE* f, const void* data, int size) {
    const SPacketCGStateCheck& p = *(const SPacketCGStateCheck*)data;
    fprintf(f, "key=%lu index=%lu\n", p.key, p.index);
}

inline void Print_TPacketCGPong(FILE* f, const void* data, int size) {
    const TPacketCGPong& p = *(const TPacketCGPong*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketCGHandshake(FILE* f, const void* data, int size) {
    const TPacketCGHandshake& p = *(const TPacketCGHandshake*)data;
    fprintf(f, "dwHandshake=%u dwTime=%u lDelta=%d\n", p.dwHandshake, p.dwTime, p.lDelta);
}

inline void Print_TPacketGCCharacterAdd(FILE* f, const void* data, int size) {
    const TPacketGCCharacterAdd& p = *(const TPacketGCCharacterAdd*)data;
    fprintf(f, "dwVID=%u angle=%.2f bType=%u wRaceNum=%u bMovingSpeed=%u bAttackSpeed=%u bStateFlag=%u dwAffectFlag=[2]\n", p.dwVID, p.angle, p.bType, p.wRaceNum, p.bMovingSpeed, p.bAttackSpeed, p.bStateFlag);
}

inline void Print_TPacketGCCharacterDelete(FILE* f, const void* data, int size) {
    const TPacketGCCharacterDelete& p = *(const TPacketGCCharacterDelete*)data;
    fprintf(f, "id=%u\n", p.id);
}

inline void Print_TPacketGCMove(FILE* f, const void* data, int size) {
    const TPacketGCMove& p = *(const TPacketGCMove*)data;
    fprintf(f, "bFunc=%u bArg=%u bRot=%u dwVID=%u lX=%d lY=%d dwTime=%u dwDuration=%u\n", p.bFunc, p.bArg, p.bRot, p.dwVID, p.lX, p.lY, p.dwTime, p.dwDuration);
}

inline void Print_TPacketGCChat(FILE* f, const void* data, int size) {
    const TPacketGCChat& p = *(const TPacketGCChat*)data;
    fprintf(f, "size=%u type=%u id=%u bEmpire=%u\n", p.size, p.type, p.id, p.bEmpire);
}

inline void Print_TPacketGCSyncPosition(FILE* f, const void* data, int size) {
    const TPacketGCSyncPosition& p = *(const TPacketGCSyncPosition*)data;
    fprintf(f, "wSize=%u\n", p.wSize);
}

inline void Print_TPacketGCLoginSuccess(FILE* f, const void* data, int size) {
    const TPacketGCLoginSuccess& p = *(const TPacketGCLoginSuccess*)data;
    fprintf(f, "players=(struct) guild_id=[PLAYER_PER_ACCOUNT] handle=%u random_key=%u\n", p.handle, p.random_key);
}

inline void Print_TPacketGCLoginFailure(FILE* f, const void* data, int size) {
    const TPacketGCLoginFailure& p = *(const TPacketGCLoginFailure*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketGCCharacterCreateSuccess(FILE* f, const void* data, int size) {
    const TPacketGCCharacterCreateSuccess& p = *(const TPacketGCCharacterCreateSuccess*)data;
    fprintf(f, "bAccountCharacterIndex=%u player=(struct)\n", p.bAccountCharacterIndex);
}

inline void Print_TPacketGCCharacterCreateFailure(FILE* f, const void* data, int size) {
    const TPacketGCCharacterCreateFailure& p = *(const TPacketGCCharacterCreateFailure*)data;
    fprintf(f, "bType=%u\n", p.bType);
}

inline void Print_TPacketGCCharacterDeleteSuccess(FILE* f, const void* data, int size) {
    const TPacketGCCharacterDeleteSuccess& p = *(const TPacketGCCharacterDeleteSuccess*)data;
    fprintf(f, "account_index=%u\n", p.account_index);
}

inline void Print_TPacketGCStun(FILE* f, const void* data, int size) {
    const TPacketGCStun& p = *(const TPacketGCStun*)data;
    fprintf(f, "vid=%u\n", p.vid);
}

inline void Print_TPacketGCDead(FILE* f, const void* data, int size) {
    const TPacketGCDead& p = *(const TPacketGCDead*)data;
    fprintf(f, "vid=%u\n", p.vid);
}

inline void Print_TPacketGCCharacterPoints(FILE* f, const void* data, int size) {
    const TPacketGCCharacterPoints& p = *(const TPacketGCCharacterPoints*)data;
    fprintf(f, "points=[POINT_MAX_NUM]\n");
}

inline void Print_TPacketGCCharacterPointChange(FILE* f, const void* data, int size) {
    const TPacketGCCharacterPointChange& p = *(const TPacketGCCharacterPointChange*)data;
    fprintf(f, "dwVID=%u type=%u amount=%lld value=%lld\n", p.dwVID, p.type, (long long)p.amount, (long long)p.value);
}

inline void Print_TPacketGCChangeSpeed(FILE* f, const void* data, int size) {
    const TPacketGCChangeSpeed& p = *(const TPacketGCChangeSpeed*)data;
    fprintf(f, "vid=%u moving_speed=%u\n", p.vid, p.moving_speed);
}

inline void Print_TPacketGCCharacterUpdate(FILE* f, const void* data, int size) {
    const TPacketGCCharacterUpdate& p = *(const TPacketGCCharacterUpdate*)data;
    fprintf(f, "dwVID=%u awPart=[CHR_EQUIPPART_NUM] bMovingSpeed=%u bAttackSpeed=%u bStateFlag=%u dwAffectFlag=[2] dwGuildID=%u sAlignment=%d bPKMode=%u dwMountVnum=%u\n", p.dwVID, p.bMovingSpeed, p.bAttackSpeed, p.bStateFlag, p.dwGuildID, p.sAlignment, p.bPKMode, p.dwMountVnum);
}

inline void Print_TPacketGCItemDel(FILE* f, const void* data, int size) {
    const TPacketGCItemDel& p = *(const TPacketGCItemDel*)data;
    fprintf(f, "pos=%u\n", (unsigned)p.pos);
}

inline void Print_TPacketGCItemSet(FILE* f, const void* data, int size) {
    const TPacketGCItemSet& p = *(const TPacketGCItemSet*)data;
    fprintf(f, "Cell=(struct) vnum=%u count=%u flags=%u anti_flags=%u highlight=%u alSockets=[ITEM_SOCKET_MAX_NUM] aAttr=(struct)\n", p.vnum, (unsigned)p.count, p.flags, p.anti_flags, p.highlight);
}

inline void Print_TPacketGCItemUpdate(FILE* f, const void* data, int size) {
    const TPacketGCItemUpdate& p = *(const TPacketGCItemUpdate*)data;
    fprintf(f, "Cell=(struct) count=%u alSockets=[ITEM_SOCKET_MAX_NUM] aAttr=(struct)\n", (unsigned)p.count);
}

inline void Print_TPacketGCItemGroundAdd(FILE* f, const void* data, int size) {
    const TPacketGCItemGroundAdd& p = *(const TPacketGCItemGroundAdd*)data;
    fprintf(f, "dwVID=%u dwVnum=%u\n", p.dwVID, p.dwVnum);
}

inline void Print_TPacketGCItemGroundDel(FILE* f, const void* data, int size) {
    const TPacketGCItemGroundDel& p = *(const TPacketGCItemGroundDel*)data;
    fprintf(f, "dwVID=%u\n", p.dwVID);
}

inline void Print_TPacketGCQuickslotAdd(FILE* f, const void* data, int size) {
    const TPacketGCQuickslotAdd& p = *(const TPacketGCQuickslotAdd*)data;
    fprintf(f, "pos=%u slot=(struct)\n", p.pos);
}

inline void Print_TPacketGCQuickslotDel(FILE* f, const void* data, int size) {
    const TPacketGCQuickslotDel& p = *(const TPacketGCQuickslotDel*)data;
    fprintf(f, "pos=%u\n", p.pos);
}

inline void Print_TPacketGCQuickslotSwap(FILE* f, const void* data, int size) {
    const TPacketGCQuickslotSwap& p = *(const TPacketGCQuickslotSwap*)data;
    fprintf(f, "pos=%u pos_to=%u\n", p.pos, p.pos_to);
}

inline void Print_TPacketGCItemOwnership(FILE* f, const void* data, int size) {
    const TPacketGCItemOwnership& p = *(const TPacketGCItemOwnership*)data;
    fprintf(f, "dwVID=%u\n", p.dwVID);
}

inline void Print_TPacketGCWhisper(FILE* f, const void* data, int size) {
    const TPacketGCWhisper& p = *(const TPacketGCWhisper*)data;
    fprintf(f, "wSize=%u bType=%u\n", p.wSize, p.bType);
}

inline void Print_TPacketGCMotion(FILE* f, const void* data, int size) {
    const TPacketGCMotion& p = *(const TPacketGCMotion*)data;
    fprintf(f, "vid=%u victim_vid=%u motion=%u\n", p.vid, p.victim_vid, p.motion);
}

inline void Print_TPacketGCShop(FILE* f, const void* data, int size) {
    const TPacketGCShop& p = *(const TPacketGCShop*)data;
    fprintf(f, "size=%u subheader=%u\n", p.size, p.subheader);
}

inline void Print_TPacketGCShopSign(FILE* f, const void* data, int size) {
    const TPacketGCShopSign& p = *(const TPacketGCShopSign*)data;
    fprintf(f, "dwVID=%u\n", p.dwVID);
}

inline void Print_TPacketGCDuelStart(FILE* f, const void* data, int size) {
    const TPacketGCDuelStart& p = *(const TPacketGCDuelStart*)data;
    fprintf(f, "wSize=%u\n", p.wSize);
}

inline void Print_TPacketGCPvp(FILE* f, const void* data, int size) {
    const TPacketGCPvp& p = *(const TPacketGCPvp*)data;
    fprintf(f, "dwVIDSrc=%u dwVIDDst=%u bMode=%u\n", p.dwVIDSrc, p.dwVIDDst, p.bMode);
}

inline void Print_TPacketGCExchange(FILE* f, const void* data, int size) {
    const TPacketGCExchange& p = *(const TPacketGCExchange*)data;
    fprintf(f, "sub_header=%u is_me=%u arg1=%u arg2=(struct) arg3=%u alSockets=[ITEM_SOCKET_MAX_NUM] aAttr=(struct)\n", p.sub_header, p.is_me, p.arg1, p.arg3);
}

inline void Print_TPacketGCCharacterPosition(FILE* f, const void* data, int size) {
    const TPacketGCCharacterPosition& p = *(const TPacketGCCharacterPosition*)data;
    fprintf(f, "vid=%u position=%u\n", p.vid, p.position);
}

inline void Print_TPacketGCPing(FILE* f, const void* data, int size) {
    const TPacketGCPing& p = *(const TPacketGCPing*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketGCScript(FILE* f, const void* data, int size) {
    const TPacketGCScript& p = *(const TPacketGCScript*)data;
    fprintf(f, "size=%u skin=%u src_size=%u\n", p.size, p.skin, p.src_size);
}

inline void Print_TPacketGCQuestConfirm(FILE* f, const void* data, int size) {
    const TPacketGCQuestConfirm& p = *(const TPacketGCQuestConfirm*)data;
    fprintf(f, "timeout=%ld requestPID=%u\n", p.timeout, p.requestPID);
}

inline void Print_TPacketGCTargetInfo(FILE* f, const void* data, int size) {
    const TPacketGCTargetInfo& p = *(const TPacketGCTargetInfo*)data;
    fprintf(f, "dwVID=%u race=%u dwVnum=%u count=%u\n", p.dwVID, p.race, p.dwVnum, p.count);
}

inline void Print_TPacketGCOwnership(FILE* f, const void* data, int size) {
    const TPacketGCOwnership& p = *(const TPacketGCOwnership*)data;
    fprintf(f, "dwOwnerVID=%u dwVictimVID=%u\n", p.dwOwnerVID, p.dwVictimVID);
}

inline void Print_TPacketGCTarget(FILE* f, const void* data, int size) {
    const TPacketGCTarget& p = *(const TPacketGCTarget*)data;
    fprintf(f, "dwVID=%u bHPPercent=%u\n", p.dwVID, p.bHPPercent);
}

inline void Print_TPacketGCWarp(FILE* f, const void* data, int size) {
    const TPacketGCWarp& p = *(const TPacketGCWarp*)data;
    fprintf(f, "lX=%ld lY=%ld lAddr=%ld wPort=%u\n", p.lX, p.lY, p.lAddr, p.wPort);
}

inline void Print_TPacketGCAddFlyTargeting(FILE* f, const void* data, int size) {
    const TPacketGCAddFlyTargeting& p = *(const TPacketGCAddFlyTargeting*)data;
    fprintf(f, "dwShooterVID=%u dwTargetVID=%u\n", p.dwShooterVID, p.dwTargetVID);
}

inline void Print_TPacketGCCreateFly(FILE* f, const void* data, int size) {
    const TPacketGCCreateFly& p = *(const TPacketGCCreateFly*)data;
    fprintf(f, "bType=%u dwStartVID=%u dwEndVID=%u\n", p.bType, p.dwStartVID, p.dwEndVID);
}

inline void Print_TPacketGCMessenger(FILE* f, const void* data, int size) {
    const TPacketGCMessenger& p = *(const TPacketGCMessenger*)data;
    fprintf(f, "size=%u subheader=%u\n", p.size, p.subheader);
}

inline void Print_TPacketGCGuild(FILE* f, const void* data, int size) {
    const TPacketGCGuild& p = *(const TPacketGCGuild*)data;
    fprintf(f, "size=%u subheader=%u\n", p.size, p.subheader);
}

inline void Print_TPacketGCSkillLevel(FILE* f, const void* data, int size) {
    const TPacketGCSkillLevel& p = *(const TPacketGCSkillLevel*)data;
    fprintf(f, "skills=(struct)\n");
}

inline void Print_TPacketGCPartyInvite(FILE* f, const void* data, int size) {
    const TPacketGCPartyInvite& p = *(const TPacketGCPartyInvite*)data;
    fprintf(f, "leader_vid=%u\n", p.leader_vid);
}

inline void Print_TPacketGCPartyAdd(FILE* f, const void* data, int size) {
    const TPacketGCPartyAdd& p = *(const TPacketGCPartyAdd*)data;
    fprintf(f, "pid=%u\n", p.pid);
}

inline void Print_TPacketGCPartyUpdate(FILE* f, const void* data, int size) {
    const TPacketGCPartyUpdate& p = *(const TPacketGCPartyUpdate*)data;
    fprintf(f, "pid=%u role=%u percent_hp=%u affects=[7]\n", p.pid, p.role, p.percent_hp);
}

inline void Print_TPacketGCPartyRemove(FILE* f, const void* data, int size) {
    const TPacketGCPartyRemove& p = *(const TPacketGCPartyRemove*)data;
    fprintf(f, "pid=%u\n", p.pid);
}

inline void Print_TPacketGCQuestInfo(FILE* f, const void* data, int size) {
    const TPacketGCQuestInfo& p = *(const TPacketGCQuestInfo*)data;
    fprintf(f, "size=%u index=%u flag=%u\n", p.size, p.index, p.flag);
}

inline void Print_TPacketGCPartyParameter(FILE* f, const void* data, int size) {
    const TPacketGCPartyParameter& p = *(const TPacketGCPartyParameter*)data;
    fprintf(f, "bDistributeMode=%u\n", p.bDistributeMode);
}

inline void Print_TPacketGCSafeboxWrongPassword(FILE* f, const void* data, int size) {
    const TPacketGCSafeboxWrongPassword& p = *(const TPacketGCSafeboxWrongPassword*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketGCSafeboxSize(FILE* f, const void* data, int size) {
    const TPacketGCSafeboxSize& p = *(const TPacketGCSafeboxSize*)data;
    fprintf(f, "bSize=%u\n", p.bSize);
}

inline void Print_TPacketGCFishing(FILE* f, const void* data, int size) {
    const TPacketGCFishing& p = *(const TPacketGCFishing*)data;
    fprintf(f, "subheader=%u info=%u dir=%u\n", p.subheader, p.info, p.dir);
}

inline void Print_TPacketGCEmpire(FILE* f, const void* data, int size) {
    const TPacketGCEmpire& p = *(const TPacketGCEmpire*)data;
    fprintf(f, "bEmpire=%u\n", p.bEmpire);
}

inline void Print_TPacketGCPartyLink(FILE* f, const void* data, int size) {
    const TPacketGCPartyLink& p = *(const TPacketGCPartyLink*)data;
    fprintf(f, "pid=%u vid=%u\n", p.pid, p.vid);
}

inline void Print_TPacketGCPartyUnlink(FILE* f, const void* data, int size) {
    const TPacketGCPartyUnlink& p = *(const TPacketGCPartyUnlink*)data;
    fprintf(f, "pid=%u vid=%u\n", p.pid, p.vid);
}

inline void Print_TPacketGCViewEquip(FILE* f, const void* data, int size) {
    const TPacketGCViewEquip& p = *(const TPacketGCViewEquip*)data;
    fprintf(f, "vid=%u equips=(struct)\n", p.vid);
}

inline void Print_TPacketGCMarkBlock(FILE* f, const void* data, int size) {
    const TPacketGCMarkBlock& p = *(const TPacketGCMarkBlock*)data;
    fprintf(f, "bufSize=%u imgIdx=%u count=%u\n", p.bufSize, p.imgIdx, p.count);
}

inline void Print_TPacketGCMarkIdxlist(FILE* f, const void* data, int size) {
    const TPacketGCMarkIdxlist& p = *(const TPacketGCMarkIdxlist*)data;
    fprintf(f, "bufSize=%u count=%u\n", p.bufSize, p.count);
}

inline void Print_TPacketGCTime(FILE* f, const void* data, int size) {
    const TPacketGCTime& p = *(const TPacketGCTime*)data;
    fprintf(f, "time=%u\n", p.time);
}

inline void Print_TPacketGCChangeName(FILE* f, const void* data, int size) {
    const TPacketGCChangeName& p = *(const TPacketGCChangeName*)data;
    fprintf(f, "pid=%u\n", p.pid);
}

inline void Print_TPacketGCDungeon(FILE* f, const void* data, int size) {
    const TPacketGCDungeon& p = *(const TPacketGCDungeon*)data;
    fprintf(f, "size=%u subheader=%u\n", p.size, p.subheader);
}

inline void Print_TPacketGCWalkMode(FILE* f, const void* data, int size) {
    const TPacketGCWalkMode& p = *(const TPacketGCWalkMode*)data;
    fprintf(f, "vid=%u mode=%u\n", p.vid, p.mode);
}

inline void Print_SPacketGCChangeSkillGroup(FILE* f, const void* data, int size) {
    const SPacketGCChangeSkillGroup& p = *(const SPacketGCChangeSkillGroup*)data;
    fprintf(f, "skill_group=%u\n", p.skill_group);
}

inline void Print_TPacketGCMainCharacter(FILE* f, const void* data, int size) {
    const TPacketGCMainCharacter& p = *(const TPacketGCMainCharacter*)data;
    fprintf(f, "dwVID=%u wRaceNum=%u empire=%u skill_group=%u\n", p.dwVID, p.wRaceNum, p.empire, p.skill_group);
}

inline void Print_TPacketGCSpecialEffect(FILE* f, const void* data, int size) {
    const TPacketGCSpecialEffect& p = *(const TPacketGCSpecialEffect*)data;
    fprintf(f, "type=%u vid=%u\n", p.type, p.vid);
}

inline void Print_SPacketGCNPCPosition(FILE* f, const void* data, int size) {
    const SPacketGCNPCPosition& p = *(const SPacketGCNPCPosition*)data;
    fprintf(f, "size=%u count=%u\n", p.size, p.count);
}

inline void Print_TPacketGCLoginKey(FILE* f, const void* data, int size) {
    const TPacketGCLoginKey& p = *(const TPacketGCLoginKey*)data;
    fprintf(f, "dwLoginKey=%u\n", p.dwLoginKey);
}

inline void Print_TPacketGCRefineInformation(FILE* f, const void* data, int size) {
    const TPacketGCRefineInformation& p = *(const TPacketGCRefineInformation*)data;
    fprintf(f, "type=%u pos=%u src_vnum=%u result_vnum=%u material_count=%u cost=%d prob=%d materials=(struct)\n", p.type, (unsigned)p.pos, p.src_vnum, p.result_vnum, p.material_count, p.cost, p.prob);
}

inline void Print_TPacketGCChannel(FILE* f, const void* data, int size) {
    const TPacketGCChannel& p = *(const TPacketGCChannel*)data;
    fprintf(f, "channel=%u\n", p.channel);
}

inline void Print_TPacketGCTargetUpdate(FILE* f, const void* data, int size) {
    const TPacketGCTargetUpdate& p = *(const TPacketGCTargetUpdate*)data;
    fprintf(f, "lID=%ld\n", p.lID);
}

inline void Print_TPacketGCTargetDelete(FILE* f, const void* data, int size) {
    const TPacketGCTargetDelete& p = *(const TPacketGCTargetDelete*)data;
    fprintf(f, "lID=%ld\n", p.lID);
}

inline void Print_TPacketGCTargetCreate(FILE* f, const void* data, int size) {
    const TPacketGCTargetCreate& p = *(const TPacketGCTargetCreate*)data;
    fprintf(f, "lID=%ld dwVID=%u bType=%u\n", p.lID, p.dwVID, p.bType);
}

inline void Print_TPacketGCAffectAdd(FILE* f, const void* data, int size) {
    const TPacketGCAffectAdd& p = *(const TPacketGCAffectAdd*)data;
    fprintf(f, "(header only)\n");
}

inline void Print_TPacketGCAffectRemove(FILE* f, const void* data, int size) {
    const TPacketGCAffectRemove& p = *(const TPacketGCAffectRemove*)data;
    fprintf(f, "dwType=%u bApplyOn=%u\n", p.dwType, p.bApplyOn);
}

inline void Print_TPacketGCLandList(FILE* f, const void* data, int size) {
    const TPacketGCLandList& p = *(const TPacketGCLandList*)data;
    fprintf(f, "size=%u\n", p.size);
}

inline void Print_TPacketGCLoverInfo(FILE* f, const void* data, int size) {
    const TPacketGCLoverInfo& p = *(const TPacketGCLoverInfo*)data;
    fprintf(f, "love_point=%u\n", p.love_point);
}

inline void Print_TPacketGCLovePointUpdate(FILE* f, const void* data, int size) {
    const TPacketGCLovePointUpdate& p = *(const TPacketGCLovePointUpdate*)data;
    fprintf(f, "love_point=%u\n", p.love_point);
}

inline void Print_TPacketGCSymbolData(FILE* f, const void* data, int size) {
    const TPacketGCSymbolData& p = *(const TPacketGCSymbolData*)data;
    fprintf(f, "size=%u guild_id=%u\n", p.size, p.guild_id);
}

inline void Print_TPacketGCDigMotion(FILE* f, const void* data, int size) {
    const TPacketGCDigMotion& p = *(const TPacketGCDigMotion*)data;
    fprintf(f, "vid=%u target_vid=%u count=%u\n", p.vid, p.target_vid, p.count);
}

inline void Print_TPacketGCDamageInfo(FILE* f, const void* data, int size) {
    const TPacketGCDamageInfo& p = *(const TPacketGCDamageInfo*)data;
    fprintf(f, "dwVID=%u flag=%u damage=%d\n", p.dwVID, p.flag, p.damage);
}

inline void Print_TPacketGCCharacterAdditionalInfo(FILE* f, const void* data, int size) {
    const TPacketGCCharacterAdditionalInfo& p = *(const TPacketGCCharacterAdditionalInfo*)data;
    fprintf(f, "dwVID=%u awPart=[CHR_EQUIPPART_NUM] bEmpire=%u dwGuildID=%u dwLevel=%u sAlignment=%d bPKMode=%u dwMountVnum=%u\n", p.dwVID, p.bEmpire, p.dwGuildID, p.dwLevel, p.sAlignment, p.bPKMode, p.dwMountVnum);
}

inline void Print_TPacketGCMainCharacter3Bgm(FILE* f, const void* data, int size) {
    const TPacketGCMainCharacter3Bgm& p = *(const TPacketGCMainCharacter3Bgm*)data;
    fprintf(f, "dwVID=%u wRaceNum=%u empire=%u skill_group=%u\n", p.dwVID, p.wRaceNum, p.empire, p.skill_group);
}

inline void Print_TPacketGCMainCharacter4BgmVol(FILE* f, const void* data, int size) {
    const TPacketGCMainCharacter4BgmVol& p = *(const TPacketGCMainCharacter4BgmVol*)data;
    fprintf(f, "dwVID=%u wRaceNum=%u fBGMVol=%.2f empire=%u skill_group=%u\n", p.dwVID, p.wRaceNum, p.fBGMVol, p.empire, p.skill_group);
}

inline void Print_TPacketGCAuthSuccess(FILE* f, const void* data, int size) {
    const TPacketGCAuthSuccess& p = *(const TPacketGCAuthSuccess*)data;
    fprintf(f, "dwLoginKey=%u bResult=%u\n", p.dwLoginKey, p.bResult);
}

inline void Print_SPacketGCHybridCryptKeys(FILE* f, const void* data, int size) {
    const SPacketGCHybridCryptKeys& p = *(const SPacketGCHybridCryptKeys*)data;
    fprintf(f, "uint8_t=[iStreamSize] uint8_t=[uDynamicPacketSize] m_pStream=%u uDynamicPacketSize=%u KeyStreamLen=%d\n", (unsigned)p.m_pStream, p.uDynamicPacketSize, p.KeyStreamLen);
}

inline void Print_SPacketGCPackageSDB(FILE* f, const void* data, int size) {
    const SPacketGCPackageSDB& p = *(const SPacketGCPackageSDB*)data;
    fprintf(f, "uint8_t=[iStreamSize] uint8_t=[uDynamicPacketSize] m_pStream=%u uDynamicPacketSize=%u iStreamLen=%d\n", (unsigned)p.m_pStream, p.uDynamicPacketSize, p.iStreamLen);
}

inline void Print_TPacketGCSwitchbot(FILE* f, const void* data, int size) {
    const TPacketGCSwitchbot& p = *(const TPacketGCSwitchbot*)data;
    fprintf(f, "size=%d subheader=%u slot=%u\n", p.size, p.subheader, p.slot);
}

inline void Print_TPacketGCSpecificEffect(FILE* f, const void* data, int size) {
    const TPacketGCSpecificEffect& p = *(const TPacketGCSpecificEffect*)data;
    fprintf(f, "vid=%u effect_file='%s'\n", p.vid, p.effect_file);
}

inline void Print_TPacketGCDragonSoulRefine(FILE* f, const void* data, int size) {
    const TPacketGCDragonSoulRefine& p = *(const TPacketGCDragonSoulRefine*)data;
    fprintf(f, "bSubType=%u Pos=(struct)\n", p.bSubType);
}

inline void Print_TPacketGCPhase(FILE* f, const void* data, int size) {
    const TPacketGCPhase& p = *(const TPacketGCPhase*)data;
    fprintf(f, "phase=%u\n", p.phase);
}

inline void Print_TPacketGCHandshake(FILE* f, const void* data, int size) {
    const TPacketGCHandshake& p = *(const TPacketGCHandshake*)data;
    fprintf(f, "dwHandshake=%u dwTime=%u lDelta=%ld\n", p.dwHandshake, p.dwTime, p.lDelta);
}

//=============================================================================
// Auto Registration
//=============================================================================
inline void RegisterAllPacketsGenerated()
{
    auto& dbg = CPacketDebug::Instance();

    //-------------------------------------------------------------------------
    // Client -> Server (CG) - 71 packets
    //-------------------------------------------------------------------------
    dbg.RegSend(HEADER_CG_LOGIN, "CG_LOGIN", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_ATTACK, "CG_ATTACK", Print_TPacketCGAttack);
    dbg.RegSend(HEADER_CG_CHAT, "CG_CHAT", Print_TPacketCGChat); // variable size
    dbg.RegSend(HEADER_CG_CHARACTER_CREATE, "CG_CHARACTER_CREATE", Print_TPacketCGCharacterCreate);
    dbg.RegSend(HEADER_CG_CHARACTER_DELETE, "CG_CHARACTER_DELETE", Print_TPacketCGCharacterDelete);
    dbg.RegSend(HEADER_CG_CHARACTER_SELECT, "CG_CHARACTER_SELECT", Print_TPacketCGCharacterSelect);
    dbg.RegSend(HEADER_CG_MOVE, "CG_MOVE", Print_TPacketCGMove);
    dbg.RegSend(HEADER_CG_SYNC_POSITION, "CG_SYNC_POSITION", Print_TPacketCGSyncPosition); // variable size
    dbg.RegSend(HEADER_CG_ENTERGAME, "CG_ENTERGAME", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_ITEM_USE, "CG_ITEM_USE", Print_TPacketCGItemUse);
    dbg.RegSend(HEADER_CG_ITEM_MOVE, "CG_ITEM_MOVE", Print_TPacketCGItemMove);
    dbg.RegSend(HEADER_CG_ITEM_PICKUP, "CG_ITEM_PICKUP", Print_TPacketCGItemPickup);
    dbg.RegSend(HEADER_CG_QUICKSLOT_ADD, "CG_QUICKSLOT_ADD", Print_TPacketCGQuickslotAdd);
    dbg.RegSend(HEADER_CG_QUICKSLOT_DEL, "CG_QUICKSLOT_DEL", Print_TPacketCGQuickslotDel);
    dbg.RegSend(HEADER_CG_QUICKSLOT_SWAP, "CG_QUICKSLOT_SWAP", Print_TPacketCGQuickslotSwap);
    dbg.RegSend(HEADER_CG_WHISPER, "CG_WHISPER", Print_TPacketCGWhisper); // variable size
    dbg.RegSend(HEADER_CG_ITEM_DROP, "CG_ITEM_DROP", Print_TPacketCGItemDrop);
    dbg.RegSend(HEADER_CG_ON_CLICK, "CG_ON_CLICK", Print_TPacketCGOnClick);
    dbg.RegSend(HEADER_CG_EXCHANGE, "CG_EXCHANGE", Print_TPacketCGExchange);
    dbg.RegSend(HEADER_CG_CHARACTER_POSITION, "CG_CHARACTER_POSITION", Print_TPacketCGCharacterPosition);
    dbg.RegSend(HEADER_CG_SCRIPT_ANSWER, "CG_SCRIPT_ANSWER", Print_TPacketCGScriptAnswer);
    dbg.RegSend(HEADER_CG_QUEST_INPUT_STRING, "CG_QUEST_INPUT_STRING", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_QUEST_CONFIRM, "CG_QUEST_CONFIRM", Print_TPacketCGQuestConfirm);
    dbg.RegSend(HEADER_CG_SHOP, "CG_SHOP", Print_TPacketCGShop);
    dbg.RegSend(HEADER_CG_FLY_TARGETING, "CG_FLY_TARGETING", PrintHexDump); // no struct found
    dbg.RegSend(HEADER_CG_USE_SKILL, "CG_USE_SKILL", Print_TPacketCGUseSkill);
    dbg.RegSend(HEADER_CG_ADD_FLY_TARGETING, "CG_ADD_FLY_TARGETING", Print_TPacketCGAddFlyTargeting);
    dbg.RegSend(HEADER_CG_SHOOT, "CG_SHOOT", Print_TPacketCGShoot);
    dbg.RegSend(HEADER_CG_MYSHOP, "CG_MYSHOP", Print_SPacketCGMyShop);
    dbg.RegSend(HEADER_CG_TARGET_INFO_LOAD, "CG_TARGET_INFO_LOAD", Print_TPacketCGTargetInfoLoad);
    dbg.RegSend(HEADER_CG_ITEM_USE_TO_ITEM, "CG_ITEM_USE_TO_ITEM", Print_TPacketCGItemUseToItem);
    dbg.RegSend(HEADER_CG_TARGET, "CG_TARGET", Print_TPacketCGTarget);
    dbg.RegSend(HEADER_CG_WARP, "CG_WARP", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_SCRIPT_BUTTON, "CG_SCRIPT_BUTTON", Print_TPacketCGScriptButton);
    dbg.RegSend(HEADER_CG_MESSENGER, "CG_MESSENGER", Print_TPacketCGMessenger);
    dbg.RegSend(HEADER_CG_MALL_CHECKOUT, "CG_MALL_CHECKOUT", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegSend(HEADER_CG_SAFEBOX_CHECKIN, "CG_SAFEBOX_CHECKIN", Print_TPacketCGSafeboxCheckin);
    dbg.RegSend(HEADER_CG_SAFEBOX_CHECKOUT, "CG_SAFEBOX_CHECKOUT", Print_TPacketCGSafeboxCheckout);
    dbg.RegSend(HEADER_CG_PARTY_INVITE, "CG_PARTY_INVITE", Print_TPacketCGPartyInvite);
    dbg.RegSend(HEADER_CG_PARTY_INVITE_ANSWER, "CG_PARTY_INVITE_ANSWER", Print_TPacketCGPartyInviteAnswer);
    dbg.RegSend(HEADER_CG_PARTY_REMOVE, "CG_PARTY_REMOVE", Print_TPacketCGPartyRemove);
    dbg.RegSend(HEADER_CG_PARTY_SET_STATE, "CG_PARTY_SET_STATE", Print_TPacketCGPartySetState);
    dbg.RegSend(HEADER_CG_PARTY_USE_SKILL, "CG_PARTY_USE_SKILL", Print_TPacketCGPartyUseSkill);
    dbg.RegSend(HEADER_CG_SAFEBOX_ITEM_MOVE, "CG_SAFEBOX_ITEM_MOVE", Print_TPacketCGItemMove);
    dbg.RegSend(HEADER_CG_PARTY_PARAMETER, "CG_PARTY_PARAMETER", Print_TPacketCGPartyParameter);
    dbg.RegSend(HEADER_CG_GUILD, "CG_GUILD", Print_TPacketCGGuild);
    dbg.RegSend(HEADER_CG_ANSWER_MAKE_GUILD, "CG_ANSWER_MAKE_GUILD", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_FISHING, "CG_FISHING", Print_TPacketCGFishing);
    dbg.RegSend(HEADER_CG_GIVE_ITEM, "CG_GIVE_ITEM", Print_TPacketCGGiveItem);
    dbg.RegSend(HEADER_CG_EMPIRE, "CG_EMPIRE", Print_TPacketCGEmpire);
    dbg.RegSend(HEADER_CG_REFINE, "CG_REFINE", Print_TPacketCGRefine);
    dbg.RegSend(HEADER_CG_MARK_LOGIN, "CG_MARK_LOGIN", Print_TPacketCGMarkLogin);
    dbg.RegSend(HEADER_CG_MARK_CRCLIST, "CG_MARK_CRCLIST", Print_TPacketCGMarkCrclist);
    dbg.RegSend(HEADER_CG_MARK_UPLOAD, "CG_MARK_UPLOAD", Print_TPacketCGMarkUpload);
    dbg.RegSend(HEADER_CG_MARK_IDXLIST, "CG_MARK_IDXLIST", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_HACK, "CG_HACK", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_CHANGE_NAME, "CG_CHANGE_NAME", Print_TPacketCGChangeName);
    dbg.RegSend(HEADER_CG_LOGIN2, "CG_LOGIN2", Print_TPacketCGLogin2);
    dbg.RegSend(HEADER_CG_DUNGEON, "CG_DUNGEON", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegSend(HEADER_CG_LOGIN3, "CG_LOGIN3", Print_TPacketCGLogin3);
    dbg.RegSend(HEADER_CG_GUILD_SYMBOL_UPLOAD, "CG_GUILD_SYMBOL_UPLOAD", Print_TPacketCGGuildSymbolUpload); // variable size
    dbg.RegSend(HEADER_CG_SYMBOL_CRC, "CG_SYMBOL_CRC", Print_TPacketCGSymbolCrc); // variable size
    dbg.RegSend(HEADER_CG_SCRIPT_SELECT_ITEM, "CG_SCRIPT_SELECT_ITEM", Print_TPacketCGScriptSelectItem);
    dbg.RegSend(HEADER_CG_SWITCHBOT, "CG_SWITCHBOT", Print_TPacketCGSwitchbot);
    dbg.RegSend(HEADER_CG_DRAGON_SOUL_REFINE, "CG_DRAGON_SOUL_REFINE", Print_TPacketCGDragonSoulRefine);
    dbg.RegSend(HEADER_CG_STATE_CHECKER, "CG_STATE_CHECKER", Print_SPacketCGStateCheck);
    dbg.RegSend(HEADER_CG_CLIENT_VERSION2, "CG_CLIENT_VERSION2", PrintHexDump); // no struct found
    dbg.RegSend(HEADER_CG_TIME_SYNC, "CG_TIME_SYNC", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegSend(HEADER_CG_CLIENT_VERSION, "CG_CLIENT_VERSION", PrintHexDump); // no struct found
    dbg.RegSend(HEADER_CG_PONG, "CG_PONG", PrintHeaderOnly); // header only
    dbg.RegSend(HEADER_CG_HANDSHAKE, "CG_HANDSHAKE", Print_TPacketCGHandshake);

    //-------------------------------------------------------------------------
    // Server -> Client (GC) - 108 packets
    //-------------------------------------------------------------------------
    dbg.RegRecv(HEADER_GC_CHARACTER_ADD, "GC_CHARACTER_ADD", Print_TPacketGCCharacterAdd);
    dbg.RegRecv(HEADER_GC_CHARACTER_DELETE, "GC_CHARACTER_DELETE", Print_TPacketGCCharacterDelete);
    dbg.RegRecv(HEADER_GC_MOVE, "GC_MOVE", Print_TPacketGCMove);
    dbg.RegRecv(HEADER_GC_CHAT, "GC_CHAT", Print_TPacketGCChat); // variable size
    dbg.RegRecv(HEADER_GC_SYNC_POSITION, "GC_SYNC_POSITION", Print_TPacketGCSyncPosition); // variable size
    dbg.RegRecv(HEADER_GC_LOGIN_SUCCESS, "GC_LOGIN_SUCCESS", Print_TPacketGCLoginSuccess);
    dbg.RegRecv(HEADER_GC_LOGIN_FAILURE, "GC_LOGIN_FAILURE", PrintHeaderOnly); // header only
    dbg.RegRecv(HEADER_GC_CHARACTER_CREATE_SUCCESS, "GC_CHARACTER_CREATE_SUCCESS", Print_TPacketGCCharacterCreateSuccess);
    dbg.RegRecv(HEADER_GC_CHARACTER_CREATE_FAILURE, "GC_CHARACTER_CREATE_FAILURE", Print_TPacketGCCharacterCreateFailure);
    dbg.RegRecv(HEADER_GC_CHARACTER_DELETE_SUCCESS, "GC_CHARACTER_DELETE_SUCCESS", Print_TPacketGCCharacterDeleteSuccess);
    dbg.RegRecv(HEADER_GC_CHARACTER_DELETE_WRONG_SOCIAL_ID, "GC_CHARACTER_DELETE_WRONG_SOCIAL_ID", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_ATTACK, "GC_ATTACK", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_STUN, "GC_STUN", Print_TPacketGCStun);
    dbg.RegRecv(HEADER_GC_DEAD, "GC_DEAD", Print_TPacketGCDead);
    dbg.RegRecv(HEADER_GC_CHARACTER_POINTS, "GC_CHARACTER_POINTS", Print_TPacketGCCharacterPoints);
    dbg.RegRecv(HEADER_GC_CHARACTER_POINT_CHANGE, "GC_CHARACTER_POINT_CHANGE", Print_TPacketGCCharacterPointChange);
    dbg.RegRecv(HEADER_GC_CHANGE_SPEED, "GC_CHANGE_SPEED", Print_TPacketGCChangeSpeed);
    dbg.RegRecv(HEADER_GC_CHARACTER_UPDATE, "GC_CHARACTER_UPDATE", Print_TPacketGCCharacterUpdate);
    dbg.RegRecv(HEADER_GC_ITEM_DEL, "GC_ITEM_DEL", Print_TPacketGCItemDel);
    dbg.RegRecv(HEADER_GC_ITEM_SET, "GC_ITEM_SET", Print_TPacketGCItemSet);
    dbg.RegRecv(HEADER_GC_ITEM_DROP, "GC_ITEM_DROP", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_CHARACTER_UPDATE_NEW, "GC_CHARACTER_UPDATE_NEW", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_ITEM_UPDATE, "GC_ITEM_UPDATE", Print_TPacketGCItemUpdate);
    dbg.RegRecv(HEADER_GC_ITEM_GROUND_ADD, "GC_ITEM_GROUND_ADD", Print_TPacketGCItemGroundAdd);
    dbg.RegRecv(HEADER_GC_ITEM_GROUND_DEL, "GC_ITEM_GROUND_DEL", Print_TPacketGCItemGroundDel);
    dbg.RegRecv(HEADER_GC_QUICKSLOT_ADD, "GC_QUICKSLOT_ADD", Print_TPacketGCQuickslotAdd);
    dbg.RegRecv(HEADER_GC_QUICKSLOT_DEL, "GC_QUICKSLOT_DEL", Print_TPacketGCQuickslotDel);
    dbg.RegRecv(HEADER_GC_QUICKSLOT_SWAP, "GC_QUICKSLOT_SWAP", Print_TPacketGCQuickslotSwap);
    dbg.RegRecv(HEADER_GC_ITEM_OWNERSHIP, "GC_ITEM_OWNERSHIP", Print_TPacketGCItemOwnership);
    dbg.RegRecv(HEADER_GC_WHISPER, "GC_WHISPER", Print_TPacketGCWhisper); // variable size
    dbg.RegRecv(HEADER_GC_MOTION, "GC_MOTION", Print_TPacketGCMotion);
    dbg.RegRecv(HEADER_GC_PARTS, "GC_PARTS", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_SHOP, "GC_SHOP", Print_TPacketGCShop); // variable size
    dbg.RegRecv(HEADER_GC_SHOP_SIGN, "GC_SHOP_SIGN", Print_TPacketGCShopSign);
    dbg.RegRecv(HEADER_GC_DUEL_START, "GC_DUEL_START", Print_TPacketGCDuelStart); // variable size
    dbg.RegRecv(HEADER_GC_PVP, "GC_PVP", Print_TPacketGCPvp);
    dbg.RegRecv(HEADER_GC_EXCHANGE, "GC_EXCHANGE", Print_TPacketGCExchange);
    dbg.RegRecv(HEADER_GC_CHARACTER_POSITION, "GC_CHARACTER_POSITION", Print_TPacketGCCharacterPosition);
    dbg.RegRecv(HEADER_GC_PING, "GC_PING", PrintHeaderOnly); // header only
    dbg.RegRecv(HEADER_GC_SCRIPT, "GC_SCRIPT", Print_TPacketGCScript); // variable size
    dbg.RegRecv(HEADER_GC_QUEST_CONFIRM, "GC_QUEST_CONFIRM", Print_TPacketGCQuestConfirm);
    dbg.RegRecv(HEADER_GC_TARGET_INFO, "GC_TARGET_INFO", Print_TPacketGCTargetInfo);
    dbg.RegRecv(HEADER_GC_OWNERSHIP, "GC_OWNERSHIP", Print_TPacketGCOwnership);
    dbg.RegRecv(HEADER_GC_TARGET, "GC_TARGET", Print_TPacketGCTarget);
    dbg.RegRecv(HEADER_GC_WARP, "GC_WARP", Print_TPacketGCWarp);
    dbg.RegRecv(HEADER_GC_ADD_FLY_TARGETING, "GC_ADD_FLY_TARGETING", Print_TPacketGCAddFlyTargeting);
    dbg.RegRecv(HEADER_GC_CREATE_FLY, "GC_CREATE_FLY", Print_TPacketGCCreateFly);
    dbg.RegRecv(HEADER_GC_FLY_TARGETING, "GC_FLY_TARGETING", PrintHexDump); // no struct found
    dbg.RegRecv(HEADER_GC_MESSENGER, "GC_MESSENGER", Print_TPacketGCMessenger); // variable size
    dbg.RegRecv(HEADER_GC_GUILD, "GC_GUILD", Print_TPacketGCGuild); // variable size
    dbg.RegRecv(HEADER_GC_SKILL_LEVEL, "GC_SKILL_LEVEL", Print_TPacketGCSkillLevel);
    dbg.RegRecv(HEADER_GC_PARTY_INVITE, "GC_PARTY_INVITE", Print_TPacketGCPartyInvite);
    dbg.RegRecv(HEADER_GC_PARTY_ADD, "GC_PARTY_ADD", Print_TPacketGCPartyAdd);
    dbg.RegRecv(HEADER_GC_PARTY_UPDATE, "GC_PARTY_UPDATE", Print_TPacketGCPartyUpdate);
    dbg.RegRecv(HEADER_GC_PARTY_REMOVE, "GC_PARTY_REMOVE", Print_TPacketGCPartyRemove);
    dbg.RegRecv(HEADER_GC_QUEST_INFO, "GC_QUEST_INFO", Print_TPacketGCQuestInfo); // variable size
    dbg.RegRecv(HEADER_GC_REQUEST_MAKE_GUILD, "GC_REQUEST_MAKE_GUILD", Print_TPacketGCGuild); // variable size
    dbg.RegRecv(HEADER_GC_PARTY_PARAMETER, "GC_PARTY_PARAMETER", Print_TPacketGCPartyParameter);
    dbg.RegRecv(HEADER_GC_SAFEBOX_SET, "GC_SAFEBOX_SET", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_SAFEBOX_DEL, "GC_SAFEBOX_DEL", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_SAFEBOX_WRONG_PASSWORD, "GC_SAFEBOX_WRONG_PASSWORD", PrintHeaderOnly); // header only
    dbg.RegRecv(HEADER_GC_SAFEBOX_SIZE, "GC_SAFEBOX_SIZE", Print_TPacketGCSafeboxSize);
    dbg.RegRecv(HEADER_GC_FISHING, "GC_FISHING", Print_TPacketGCFishing);
    dbg.RegRecv(HEADER_GC_EMPIRE, "GC_EMPIRE", Print_TPacketGCEmpire);
    dbg.RegRecv(HEADER_GC_PARTY_LINK, "GC_PARTY_LINK", Print_TPacketGCPartyLink);
    dbg.RegRecv(HEADER_GC_PARTY_UNLINK, "GC_PARTY_UNLINK", Print_TPacketGCPartyUnlink);
    dbg.RegRecv(HEADER_GC_REFINE_INFORMATION_OLD, "GC_REFINE_INFORMATION_OLD", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_VIEW_EQUIP, "GC_VIEW_EQUIP", Print_TPacketGCViewEquip);
    dbg.RegRecv(HEADER_GC_MARK_BLOCK, "GC_MARK_BLOCK", Print_TPacketGCMarkBlock);
    dbg.RegRecv(HEADER_GC_MARK_IDXLIST, "GC_MARK_IDXLIST", Print_TPacketGCMarkIdxlist);
    dbg.RegRecv(HEADER_GC_TIME, "GC_TIME", Print_TPacketGCTime);
    dbg.RegRecv(HEADER_GC_CHANGE_NAME, "GC_CHANGE_NAME", Print_TPacketGCChangeName);
    dbg.RegRecv(HEADER_GC_DUNGEON, "GC_DUNGEON", Print_TPacketGCDungeon); // variable size
    dbg.RegRecv(HEADER_GC_WALK_MODE, "GC_WALK_MODE", Print_TPacketGCWalkMode);
    dbg.RegRecv(HEADER_GC_SKILL_GROUP, "GC_SKILL_GROUP", Print_SPacketGCChangeSkillGroup);
    dbg.RegRecv(HEADER_GC_MAIN_CHARACTER, "GC_MAIN_CHARACTER", Print_TPacketGCMainCharacter);
    dbg.RegRecv(HEADER_GC_SPECIAL_EFFECT, "GC_SPECIAL_EFFECT", Print_TPacketGCSpecialEffect);
    dbg.RegRecv(HEADER_GC_NPC_POSITION, "GC_NPC_POSITION", Print_SPacketGCNPCPosition); // variable size
    dbg.RegRecv(HEADER_GC_LOGIN_KEY, "GC_LOGIN_KEY", Print_TPacketGCLoginKey);
    dbg.RegRecv(HEADER_GC_REFINE_INFORMATION, "GC_REFINE_INFORMATION", Print_TPacketGCRefineInformation);
    dbg.RegRecv(HEADER_GC_CHANNEL, "GC_CHANNEL", Print_TPacketGCChannel);
    dbg.RegRecv(HEADER_GC_MALL_OPEN, "GC_MALL_OPEN", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_TARGET_UPDATE, "GC_TARGET_UPDATE", Print_TPacketGCTargetUpdate);
    dbg.RegRecv(HEADER_GC_TARGET_DELETE, "GC_TARGET_DELETE", Print_TPacketGCTargetDelete);
    dbg.RegRecv(HEADER_GC_TARGET_CREATE, "GC_TARGET_CREATE", Print_TPacketGCTargetCreate);
    dbg.RegRecv(HEADER_GC_AFFECT_ADD, "GC_AFFECT_ADD", Print_TPacketGCAffectAdd);
    dbg.RegRecv(HEADER_GC_AFFECT_REMOVE, "GC_AFFECT_REMOVE", Print_TPacketGCAffectRemove);
    dbg.RegRecv(HEADER_GC_MALL_SET, "GC_MALL_SET", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_MALL_DEL, "GC_MALL_DEL", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_LAND_LIST, "GC_LAND_LIST", Print_TPacketGCLandList); // variable size
    dbg.RegRecv(HEADER_GC_LOVER_INFO, "GC_LOVER_INFO", Print_TPacketGCLoverInfo);
    dbg.RegRecv(HEADER_GC_LOVE_POINT_UPDATE, "GC_LOVE_POINT_UPDATE", Print_TPacketGCLovePointUpdate);
    dbg.RegRecv(HEADER_GC_SYMBOL_DATA, "GC_SYMBOL_DATA", Print_TPacketGCSymbolData); // variable size
    dbg.RegRecv(HEADER_GC_DIG_MOTION, "GC_DIG_MOTION", Print_TPacketGCDigMotion);
    dbg.RegRecv(HEADER_GC_DAMAGE_INFO, "GC_DAMAGE_INFO", Print_TPacketGCDamageInfo);
    dbg.RegRecv(HEADER_GC_CHARACTER_ADDITIONAL_INFO, "GC_CHARACTER_ADDITIONAL_INFO", Print_TPacketGCCharacterAdditionalInfo);
    dbg.RegRecv(HEADER_GC_MAIN_CHARACTER3_BGM, "GC_MAIN_CHARACTER3_BGM", Print_TPacketGCMainCharacter3Bgm);
    dbg.RegRecv(HEADER_GC_MAIN_CHARACTER4_BGM_VOL, "GC_MAIN_CHARACTER4_BGM_VOL", Print_TPacketGCMainCharacter4BgmVol);
    dbg.RegRecv(HEADER_GC_AUTH_SUCCESS, "GC_AUTH_SUCCESS", Print_TPacketGCAuthSuccess);
    dbg.RegRecv(HEADER_GC_HYBRIDCRYPT_KEYS, "GC_HYBRIDCRYPT_KEYS", Print_SPacketGCHybridCryptKeys);
    dbg.RegRecv(HEADER_GC_HYBRIDCRYPT_SDB, "GC_HYBRIDCRYPT_SDB", Print_SPacketGCPackageSDB);
    dbg.RegRecv(HEADER_GC_SWITCHBOT, "GC_SWITCHBOT", Print_TPacketGCSwitchbot);
    dbg.RegRecv(HEADER_GC_SPECIFIC_EFFECT, "GC_SPECIFIC_EFFECT", Print_TPacketGCSpecificEffect);
    dbg.RegRecv(HEADER_GC_DRAGON_SOUL_REFINE, "GC_DRAGON_SOUL_REFINE", Print_TPacketGCDragonSoulRefine);
    dbg.RegRecv(HEADER_GC_RESPOND_CHANNELSTATUS, "GC_RESPOND_CHANNELSTATUS", PrintHexDump); // no struct found
    dbg.RegRecv(HEADER_GC_TIME_SYNC, "GC_TIME_SYNC", PrintHexDump); // no struct (dynamic/deprecated)
    dbg.RegRecv(HEADER_GC_PHASE, "GC_PHASE", Print_TPacketGCPhase);
    dbg.RegRecv(HEADER_GC_HANDSHAKE, "GC_HANDSHAKE", Print_TPacketGCHandshake);
}

#endif // __PACKET_DEBUG_REG_GEN_H__
